-- AlterTable
ALTER TABLE "Kudos" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "MoodResponse" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "PollResponse" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
